### ISSUE TITLE
Using Chinese to ask questions and returning garbled code

### ISSUE THREAD

**Issue by ssy040504** [KoushikNavuluri/Claude-API#1]
Using Chinese to ask questions and returning garbled code

**Comment by KoushikNavuluri** [comment]
Hello , Thanks for opening the issue and letting me know, there has been a problem in decoding content in utf-8 and it has been fixed now , You can check now... :)

![Screenshot (9)](https://github.com/KoushikNavuluri/Claude-API/assets/103725723/b1792a01-516b-4b0b-8c33-495acb285bed)
