### ISSUE TITLE
cookie error

### ISSUE THREAD

**Issue by sdimantsd** [KoushikNavuluri/Claude-API#10]
Hi
I am using this code:
```

from claude_api import Client
import os
cookie = '__cf_bm=XXXX=; sessionKey=XXXX; intercom-session-lupk8zyo=XXXX; intercom-device-id-lupk8zyo=XXXX'
# cookie = os.environ.get('cookie')
print('cookie: ', cookie)
claude_api = Client(cookie)

conversations = claude_api.list_all_conversations()
for conversation in conversations:
    conversation_id = conversation['uuid']
    print(conversation_id)

```
But I get this error:
```
Traceback (most recent call last):
  File "C:\Users\User\Documents\PycharmProjects\AutomaticEditTranscripts\main.py", line 13, in <module>
    claude_api = Client(cookie)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\claude_api.py", line 11, in __init__
    self.organization_id = self.get_organization_id()
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\claude_api.py", line 31, in get_organization_id
    uuid = res[0]['uuid']
KeyError: 0

```

Why is that?
I try to downgrade to 
claude-api==1.0.8
but it's steal happened

![image](https://github.com/KoushikNavuluri/Claude-API/assets/29533264/d0489e85-880b-464c-af5a-e17b8f1410fd)

**Comment by armbull** [comment]
So i ran this code forwardly from source library
`import requests
import json
import os
import uuid
cookie = 'sessionKey=sk-XXX intercom-device-id-lupk8zyo=XXX; intercom-session-lupk8zyo=XXX; __cf_bm=XXX'
def get_organization_id():
    url = "https://claude.ai/api/organizations"
    headers = {
        'User-Agent':
        'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0',
        'Accept-Language': 'en-US,en;q=0.5',
        'Referer': 'https://claude.ai/chats',
        'Content-Type': 'application/json',
        'Sec-Fetch-Dest': 'empty',
        'Sec-Fetch-Mode': 'cors',
        'Sec-Fetch-Site': 'same-origin',
        'Connection': 'keep-alive',
        'Cookie': f'{cookie}'
    }

    response = requests.request("GET", url, headers=headers)
    print(response)
    res = json.loads(response.text)
    uuid = res[0]['uuid']

    return uuid

if __name__ == "__main__":
    get_organization_id()`
   
And get that error
`<Response [403]>
Traceback (most recent call last):
  File "/Users/armbull/Users/Me/Dev/AI/media-pipeline/text-2-text/txt.py", line 31, in <module>
    get_organization_id()
  File "/Users/armbull/Users/Me/Dev/AI/media-pipeline/text-2-text/txt.py", line 26, in get_organization_id
    uuid = res[0]['uuid']
KeyError: 0`

Seems Error is 403

My IP is US, i have an access from browser, I've tried to change userAgent, there is no result.

**Comment by KoushikNavuluri** [comment]
Upgrade to latest version:

 pip install --upgrade claude-api

**Comment by armbull** [comment]
I am on latest version. 
There is same error.
