### ISSUE TITLE
Run the consolo_chat.py and report the following error

### ISSUE THREAD

**Issue by Henryyijun** [KoushikNavuluri/Claude-API#13]
![image](https://github.com/KoushikNavuluri/Claude-API/assets/26760101/426d4013-d91e-4cc8-ad95-e7819a43a7f7)

**Comment by wwwwar3com** [comment]
the response data seems has been encoded/compressed.

**Comment by wwwwar3com** [comment]
Actually you don't need to call Claude API to get organization id. it's right there as part of your browser URL, 
So you can hard code the org id , you may want to update the logic to set conversation id and you should be good to go

**Comment by KoushikNavuluri** [comment]
Might be error in your cookie placement, Please check it out once again!! @Henryyijun
