### ISSUE TITLE
authentication not working

### ISSUE THREAD

**Issue by armathor** [KoushikNavuluri/Claude-API#14]
Hi there,

nice work. But unfortunately not working on my side.

I'm getting an error when trying to execute pretty much your console_chat.py example script:

File "/Volumes/Daten_meine/jn_macbook12/Google Drive/Dokumente/Computer/Programmieren/Projekte/Python/20 Python auf "High Sierra 2" mb2016/claude2_for_hacking/first_attempt.py", line 61, in <module>
    main()
  File "/Volumes/Daten_meine/jn_macbook12/Google Drive/Dokumente/Computer/Programmieren/Projekte/Python/20 Python auf "High Sierra 2" mb2016/claude2_for_hacking/first_attempt.py", line 35, in main
    claude = Client(cookie)   
  File "/Users/jn_macbook12_6/.local/share/virtualenvs/claude2_for_hacking-7E8s7b7f/lib/python3.10/site-packages/claude_api.py", line 11, in __init__
    self.organization_id = self.get_organization_id()
  File "/Users/jn_macbook12_6/.local/share/virtualenvs/claude2_for_hacking-7E8s7b7f/lib/python3.10/site-packages/claude_api.py", line 31, in get_organization_id
    uuid = res[0]['uuid']
KeyError: 0

For debugging purpose, I isolated your function "def get_organization_id(self)" where the error happens and wrote a short debugging script for testing. Turns out that it is an authentication error. Here is my debugging script including the output:

import requests, os

url = "https://claude.ai/api/organizations"

headers = {
    'User-Agent':
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0',
    'Accept-Language': 'en-US,en;q=0.5',
    'Referer': 'https://claude.ai/chats',
    'Content-Type': 'application/json',
    'Sec-Fetch-Dest': 'empty',
    'Sec-Fetch-Mode': 'cors',
    'Sec-Fetch-Site': 'same-origin',
    'Connection': 'keep-alive',
    'Cookie': f"{os.environ.get('CLAUDE2_COOKIE')}"
}

response = requests.request("GET", url, headers=headers)
print(response.text)

prints:  
{"error":{"type":"permission_error","message":"Not authenticated"},"detail":"Not authenticated"}

I believe I haven't done something wrong. Should work, but doesn't. Maybe Anthropic has changed something within the last days? Or I'm not seeing my mistake, finally you never know. So wondering if it is still working on your side.

Best wishes!

**Comment by KoushikNavuluri** [comment]
It might be error in cookie placement. did you insert the "whole  cookie"  value like here?:
   ![Screenshot (8)](https://github.com/KoushikNavuluri/Claude-API/assets/103725723/355971e3-f46c-47fc-a3cf-008bb55bb4c6)

**Comment by armathor** [comment]
Ah ok, now it's working. 

I've only used sessonKey, but not the intercom_... stuff. Grabbed it from the "Application tab -> Storage", because yesterday I couldn't find it in the Network tab. I thought the sessionKey is enough.

Cool, am happy now. Thanks again for that nice tool! Best wishes!

**Comment by KoushikNavuluri** [comment]
Thank you, @armathor . Glad you liked it ! and Wish you the same...😊!!!
Please do follow and support for such stuff.

**Comment by TonySchneider** [comment]
getting the same error. seems like it doesn't work anymore

**Comment by armathor** [comment]
> getting the same error. seems like it doesn't work anymore

Here it "works". But a request takes almost 3 minutes to come back 😝

Since Claude2 in Chrome works normally, I would say Anthropic might have implemented something to slow down non-browser requests. Maybe through a WAF.

If that's true, then afaik we can forget about requests library. The only way that I personally know that might work to circumvent something like this is using ["undetected chromedriver"](https://github.com/ultrafunkamsterdam/undetected-chromedriver). Though I'm not a real expert here, maybe there are also other ways. And I've never tried that driver, so hands down.

**Comment by TonySchneider** [comment]
> > getting the same error. seems like it doesn't work anymore
> 
> Here it "works". But a request takes almost 3 minutes to come back 😝
> 
> Since Claude2 in Chrome works normally, I would say Anthropic might have implemented something to slow down non-browser requests. Maybe through a WAF.
> 
> If that's true, then afaik we can forget about requests library. The only way that I personally know that might work to circumvent something like this is using ["undetected chromedriver"](https://github.com/ultrafunkamsterdam/undetected-chromedriver). Though I'm not a real expert here, maybe there are also other ways. And I've never tried that driver, so hands down.

Nice, will read about this "undetected chromedriver". thanks for sharing. 
I thought I can almost browse any website with the regular chromedriver since I'm working with it a lot... but apparently, there are websites that block the regular chromedriver(?)

**Comment by armathor** [comment]
EDIT: 

Ah sorry, I forgot to activate my VPN. Now everything works normally again. 

And happy again 😁

The interesting part is now that even without activated VPN, it worked after 3 minutes. But well, don't wanna think about that too much maybe 😌

If it didn't work on your side, make sure to use the whole cookie, which consists of 4 values. You can copy the whole cookie with all 4 values from the network tab in Chrome dev tools from any request.

**Comment by TonySchneider** [comment]
> EDIT:
> 
> Ah sorry, I forgot to activate my VPN. Now everything works normally again.
> 
> And happy again 😁
> 
> The interesting part is now that even without activated VPN, it worked after 3 minutes. But well, don't wanna think about that too much maybe 😌
> 
> If it didn't work on your side, make sure to use the whole cookie, which consists of 4 values. You can copy the whole cookie with all 4 values from the network tab in Chrome dev tools from any request.

I am using VPN and copied the whole cookie but still getting the permission_error. Maybe you can share your full script, just remove the cookie values or something..

**Comment by armathor** [comment]
Regular Chromedriver can be blocked by WAFs and stuff like that. Because it's possible to see that you use an automated tool. Not sure how, but I know that Chromedriver alone won't work always cause can be detected.

**Comment by armathor** [comment]
I use this script to check if the cookie is working:


```
import requests, os


url = "https://claude.ai/api/organizations"

headers = {
    'User-Agent':
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0',
    'Accept-Language': 'en-US,en;q=0.5',
    'Referer': 'https://claude.ai/chats',
    'Content-Type': 'application/json',
    'Sec-Fetch-Dest': 'empty',
    'Sec-Fetch-Mode': 'cors',
    'Sec-Fetch-Site': 'same-origin',
    'Connection': 'keep-alive',
    'Cookie': f"{os.environ.get('CLAUDE2_COOKIE')}"
}

response = requests.request("GET", url, headers=headers)
print(response.text)
```

**Comment by armathor** [comment]
If you get a response, the cookie works.

**Comment by KoushikNavuluri** [comment]
Hey, requests via Most VPN's are being blocked by claude servers , try performing without that!

**Comment by armathor** [comment]
Really? Didn't know that, but makes sense.

Then I'm lucky with my VPN, because it works.

You can't get along on your own machine without a VPN if you live outside of the US or the UK, because Claude is only available there atm. But you could set up a VPS which is located in one of those countries and contact Claude from there.

If your VPN is not working, you could also set up your own VPN on such a VPS. I believe it's not that difficult.
