### ISSUE TITLE
We are unable to serve your request

### ISSUE THREAD

**Issue by Kongkukongku** [KoushikNavuluri/Claude-API#17]
Hi there,

Always get "We are unable to serve your request" .

I checked the cookie which was definitely correct .

Then I copied a request from Chrome-DevTools (all the headers included), run it on postman and I got this response:
`
{
    "error": {
        "type": "permission_error",
        "message": "We are unable to serve your request"
    }
}
`
But it run successfully on Chrome. 

It's hard for me be believe the same request only works on browser?

Is everyone's code still working ?

**Comment by KoushikNavuluri** [comment]
hey, can you show me your cookie sample format??

**Comment by TonySchneider** [comment]
intercom-device-id-l23k8zyo=<ID>; sessionKey=<KEY>;intercom-session-l23k8zyo=<INTERCOM>; __cf_bm=<CF-BM>=
@KoushikNavuluri

**Comment by KoushikNavuluri** [comment]
It might be error in cookie placement. did you insert the "whole  cookie"  value like here?:
   ![Screenshot (8)](https://github.com/KoushikNavuluri/Claude-API/assets/103725723/355971e3-f46c-47fc-a3cf-008bb55bb4c6)

**Comment by zenafey** [comment]
> It might be error in cookie placement. did you insert the "whole cookie" value like here?: ![Screenshot (8)](https://user-images.githubusercontent.com/103725723/253813495-355971e3-f46c-47fc-a3cf-008bb55bb4c6.png)

i have same issue, i copied the whole cookie, i also checked for cookie string by copying request in node.js fetch format

**Comment by KoushikNavuluri** [comment]
Do you guys are using VPN?
* Requests via most VPNs are being blocked by claude servers.

**Comment by zenafey** [comment]
> Do you guys are using VPN?
> 
> * Requests via most VPNs are being blocked by claude servers.

XD I cant use claude.ai without VPN, it shows error 'App unavailable in your country', and also same api but in NodeJS work properly
