### ISSUE TITLE
Attachments not working

### ISSUE THREAD

**Issue by shzcuber** [KoushikNavuluri/Claude-API#18]
This following code:

```
prompt = "Hello, Claude!"
conversation_id = claude_api.create_new_chat()['uuid']
response = claude_api.send_message(prompt, conversation_id, attachment="website_src.txt")
print(response)
```

Is not working. Comes up with this error:

![image](https://github.com/KoushikNavuluri/Claude-API/assets/60201722/3586d269-a55c-4c4e-b9cf-a55e95bbdd22)

I have a file `website_src.txt` in the same directory. I looked through your code, and it seems like if you print out `data` in line 122, there's some sort of error in the conversion.

Am I doing something wrong?

**Comment by shzcuber** [comment]
Found the error, I think.

Files that are exceedingly big don't work. The file I was trying was 5000+ lines, resulting in the value of `data` to be `{"error":{"type":"api_error","message":"Streaming error"}}`. Do you know of any way to solve this?

**Comment by shzcuber** [comment]
Actually, I tested it manually in Claude. Seems like it's over the length limit. Are you able to add a "Exceeding length limit" error so people can see if the attachment(s) are too big? Thanks.

**Comment by KoushikNavuluri** [comment]
Hey , @shzcuber thanks for the check , will update that error exception in next version of code!
