### ISSUE TITLE
Under a proxy environment, show up error

### ISSUE THREAD

**Issue by darrelwangsz** [KoushikNavuluri/Claude-API#19]
提示这个错误   {'error': {'type': 'permission_error', 'message': 'We are unable to serve your request'}}

**Comment by darrelwangsz** [comment]
Sorry , in face some problem when use a proxy  

The error ：
 {'error': {'type': 'permission_error', 'message': 'We are unable to serve your request'}}

**Comment by KoushikNavuluri** [comment]
Actually claude is blocking most requests from inappropriate proxies and also from vpn too!
