### ISSUE TITLE
Don't know how to get right cookie

### ISSUE THREAD

**Issue by HQ-Zhang-233** [KoushikNavuluri/Claude-API#20]
![image](https://github.com/KoushikNavuluri/Claude-API/assets/48396988/33c0ab0d-38b5-4275-a9b9-15e22d5d4deb)
I can't find the correct cookie. I tried a few times and failed. Please give a clearer tutorial, thank you！！！

**Comment by Amm1rr** [comment]
First, make a request (ask a question)

![Claude Cookie](https://raw.githubusercontent.com/Amm1rr/Free-Chatbot-API/master/assets/Claude.jpg)

**Comment by KoushikNavuluri** [comment]
You can also find them in storage tab !

**Comment by HQ-Zhang-233** [comment]
thanks for that~
