### ISSUE TITLE
After uploading the file, the key does not contain the uuid in the JSON

### ISSUE THREAD

**Issue by bigpong2527** [KoushikNavuluri/Claude-API#21]

**Comment by roman-prizrakjj** [comment]
cookie = os.environ.get('cookie')
replace with
cookie ="your cookies"

**Comment by KoushikNavuluri** [comment]
Hey, @bigpong2527 Please check your cookie placement properly and try.

**Comment by bigpong2527** [comment]
> Hey, @bigpong2527 Please check your cookie placement properly and try.

My cookie is correct and the returned field does not contain a uuid

**Comment by Amm1rr** [comment]
I got a similar error but for a different reason. Not sure if it's the fix, but my error was because of the cookie format. It should use this structure with the **sessionKey**:

```
sessionKey=XXXXXXXXX
```
