### ISSUE TITLE
Can stream response be implemented?  

### ISSUE THREAD

**Issue by imtzc** [KoushikNavuluri/Claude-API#23]
Can stream response be implemented?

**Comment by Amm1rr** [comment]
Claude is fast enough, but I implemented a new function called __stream_message__ for that. Let's have a look at the examples below, both on the Server and Client sides:

__[Claude Stream Response](https://github.com/Amm1rr/Free-Chatbot-API/blob/7785cd6cb85fdea26a87d0475241d4d3aecf558a/src/claude.py#L142C12-L142C12)__

__[Claude Client Example](https://github.com/Amm1rr/Free-Chatbot-API/blob/master/examples/example_claude.py)__

**Comment by imtzc** [comment]
> Claude is fast enough, but I implemented a new function called **stream_message** for that. Let's have a look at the examples below, both on the Server and Client sides:
> 
> **[Claude Stream Response](https://github.com/Amm1rr/Free-Chatbot-API/blob/7785cd6cb85fdea26a87d0475241d4d3aecf558a/src/claude.py#L142C12-L142C12)**
> 
> **[Claude Client Example](https://github.com/Amm1rr/Free-Chatbot-API/blob/master/examples/example_claude.py)**

Very good. Thank you very much.

**Comment by a2ronprice** [comment]
Is stream_message still enabled? 

<img width="539" alt="ClaudeStream" src="https://github.com/KoushikNavuluri/Claude-API/assets/107771768/dec5a48c-80b4-49b0-936d-bf821b21ad77">
