### ISSUE TITLE
Hello, the name of the session I created in Chinese to obtain the session list is garbled, how to solve it?

### ISSUE THREAD

**Issue by Apples0609** [KoushikNavuluri/Claude-API#25]
你好，我使用中文创建的会话获取会话列表的名称是乱码的，请问如何解决呢？

**Comment by KoushikNavuluri** [comment]
There is a decode fix in conversation chat names , it will be fixed in next update(soon).
If is required immediately, try this: decode the response content into utf8.

**Comment by Apples0609** [comment]
@KoushikNavuluri thanks

**Comment by KoushikNavuluri** [comment]
Please give a star if you like..and do follow and support for such cool projects!
