### ISSUE TITLE
proxy support

### ISSUE THREAD

**Issue by theurs** [KoushikNavuluri/Claude-API#26]
Could you please add proxy support. Its very easy.

# example
#proxy = {
#    'http': "socks5://172.28.1.7:1080",
#    'https': "socks5://172.28.1.7:1080",
#}

class Client:

  def __init__(self, cookie, proxy=None):
      self.proxy = proxy

and all request.get(post etc) add proxies=self.proxy

response = requests.get(url, headers=headers, proxies=self.proxy)

**Comment by KoushikNavuluri** [comment]
Sure @theurs , this is most requested and will update in next version of code.
Thanks too 😄 !
