### ISSUE TITLE
how to check if the acount is out of free messages

### ISSUE THREAD

**Issue by merlinarer** [KoushikNavuluri/Claude-API#3]
The api can also return the same massages of latest valid request if acount is out of free messages. Then, is there a way to check it?

**Comment by KoushikNavuluri** [comment]
[claude.ai](https://claude.ai/) is acually , currently there is no limit and free to use . so there is no chance of getting "out of free messages."

**Comment by merlinarer** [comment]
> 



> [claude.ai](https://claude.ai/) is acually , currently there is no limit and free to use . so there is no chance of getting "out of free messages."

Actually not, I met the same limitation after about 150 conversations as [here](https://www.reddit.com/r/ClaudeAI/comments/151djjl/does_anyone_know_what_the_message_limit_for/). At the time out of free messages, this api will always return the same massages of latest valid request.

**Comment by KoushikNavuluri** [comment]
Hey! @merlinarer , I've used more than 400  conversations a day ,i still didn't encounter such kind of issue , and as claude.ai currently is in beta in some countries, might have restricted access. (try resetting the conversations using reset_all())
Also Refer to this https://www.anthropic.com/index/claude-2 , claude.ai currently doesn't seems to have such limitations.

**Comment by merlinarer** [comment]
> Hey! @merlinarer , I've used more than 400 conversations a day ,i still didn't encounter such kind of issue , and as claude.ai currently is in beta in some countries, might have restricted access. (try resetting the conversations using reset_all()) Also Refer to this https://www.anthropic.com/index/claude-2 , claude.ai currently doesn't seems to have such limitations.

Hello, I have identified an issue with the current implementation. When there are multiple requests for conversations that involve very long contexts in a short period of time, the server responds with the message: {"error":{"type":"rate_limit_error","message":"Exceeded completions limit","code":"too_many_completions","resets_at":1689951600}}.

To handle this situation more effectively, we can add a few lines of code to check the response from the server. Here's an improved version of the code:
```
if response.status_code == 200:
        ## go on
elif response.status_code == 429:
        return "Exceeded completions limit"
else:
        raise Exception(f"Unexpected code: {response.status_code }")
```

**Comment by KoushikNavuluri** [comment]
Thanks @merlinarer for letting me know this issue. I'll surely consider this and recheck the code under such conditions and will fix it soon.
