### ISSUE TITLE
cannot get response today

### ISSUE THREAD

**Issue by HQ-Zhang-233** [KoushikNavuluri/Claude-API#32]
today cannot get the response from Claude

**Comment by HQ-Zhang-233** [comment]
still could create a new chat；but cannot get the response from Claude
but the Claude website could see the new chat and the response

**Comment by chemyibinjiang** [comment]
I also got the same problem today

**Comment by xdSora** [comment]
> While the direct response only returns an empty string now, you can still get the actual response by accessing it through the chat history:
> 
> ```python
> history = claude_api.chat_conversation_history(claude_api.list_all_conversations()[-1]["uuid"]) # latest conversation
> print(history["chat_messages"][0]["text"]) # last message
> ```
> 
> This is really annoying though, hopefully it starts working normally again.

After some testing I found out that way is not reliable. Here is a more robust way that also confirms claude actually replied to our last prompt (I am sorting the messages by date to make sure of the order):

```python
from datetime import datetime

def get_latest_reply(uuid: str) -> str:
    history = claude_api.chat_conversation_history(uuid)
    sorted_entries = sorted(history["chat_messages"], key=lambda entry: datetime.strptime(entry["created_at"], "%Y-%m-%dT%H:%M:%S.%f%z"))
    return sorted_entries[-1]["text"] if sorted_entries[-1]["sender"] == "assistant" else ""
```

**Comment by jhchenchong** [comment]
> ![截屏2023-08-09 17 52 02](https://user-images.githubusercontent.com/19201316/259368913-66a81e19-2ab3-45cf-892e-2a83a5f2a72a.png)

To replace the data parsing inside the `send_message` function, you can modify the code to something like this

**Comment by winie-hy** [comment]
It has no effect.

**Comment by HQ-Zhang-233** [comment]
> > ![截屏2023-08-09 17 52 02](https://user-images.githubusercontent.com/19201316/259368913-66a81e19-2ab3-45cf-892e-2a83a5f2a72a.png)
> 
> To replace the data parsing inside the `send_message` function, you can modify the code to something like this

this is work！！！

thanks for that~

**Comment by winie-hy** [comment]
I tried the above code change, but it is still empty?

**Comment by HQ-Zhang-233** [comment]
try to change the “send message to Claude” function into this：
` # Send Message to Claude
  def send_message(self, prompt, conversation_id, attachment=None):
    url = "https://claude.ai/api/append_message"

    # Upload attachment if provided
    attachments = []
    if attachment:
      attachment_response = self.upload_attachment(attachment)
      if attachment_response:
        attachments = [attachment_response]
      else:
        return {"Error: Invalid file format. Please try again."}

    # Ensure attachments is an empty list when no attachment is provided
    if not attachment:
      attachments = []

    payload = json.dumps({
      "completion": {
        "prompt": f"{prompt}",
        "timezone": "Asia/Kolkata",
        "model": "claude-2"
      },
      "organization_uuid": f"{self.organization_id}",
      "conversation_uuid": f"{conversation_id}",
      "text": f"{prompt}",
      "attachments": attachments
    })

    headers = {
      'User-Agent':
      'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0',
      'Accept': 'text/event-stream, text/event-stream',
      'Accept-Language': 'en-US,en;q=0.5',
      'Referer': 'https://claude.ai/chats',
      'Content-Type': 'application/json',
      'Origin': 'https://claude.ai',
      'DNT': '1',
      'Connection': 'keep-alive',
      'Cookie': f'{self.cookie}',
      'Sec-Fetch-Dest': 'empty',
      'Sec-Fetch-Mode': 'cors',
      'Sec-Fetch-Site': 'same-origin',
      'TE': 'trailers'
    }

    response = requests.post(url, headers=headers, data=payload, stream=True)
    decoded_data = response.content.decode("utf-8")
    data_strings = decoded_data.strip().split('\n')
    data_strings = [item for item in data_strings if item != '']
    completions = []
    for data_string in data_strings:
        json_str = data_string[6:].strip()
        data = json.loads(json_str)
        if 'completion' in data:
            completions.append(data['completion'])

    answer = ''.join(completions)

    # Returns answer
    return answer
`

**Comment by jstdoit** [comment]
when can you push the updated code to repo? thanks.

**Comment by winie-hy** [comment]
Can you provide a complete example

**Comment by HQ-Zhang-233** [comment]
> 

哈哈哈，北京的大佬，上面的代码是重庆的小哥写的，让他push吧，我不合适

**Comment by jstdoit** [comment]
> 

hhaha

**Comment by winie-hy** [comment]
I updated the above code, but I still got an empty reply, can you get a valid one

**Comment by HQ-Zhang-233** [comment]
> 
try this code

`from claude_api import Client
cookie =‘ your cookie here  ’

claude_api = Client(cookie)

new_chat = claude_api.create_new_chat()
conversation_id = new_chat['uuid']
print(conversation_id)

prompt = "Hello, Claude!"
response = claude_api.send_message(prompt, conversation_id)
print(response)



`

**Comment by jstdoit** [comment]
could you please make your code highlighted? haha

**Comment by jstdoit** [comment]
```python
# Send Message to Claude
def send_message(self, prompt, conversation_id, attachment=None):
url = "https://claude.ai/api/append_message"

# Upload attachment if provided
attachments = []
if attachment:
  attachment_response = self.upload_attachment(attachment)
  if attachment_response:
    attachments = [attachment_response]
  else:
    return {"Error: Invalid file format. Please try again."}

# Ensure attachments is an empty list when no attachment is provided
if not attachment:
  attachments = []

payload = json.dumps({
  "completion": {
    "prompt": f"{prompt}",
    "timezone": "Asia/Kolkata",
    "model": "claude-2"
  },
  "organization_uuid": f"{self.organization_id}",
  "conversation_uuid": f"{conversation_id}",
  "text": f"{prompt}",
  "attachments": attachments
})

headers = {
  'User-Agent':
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0',
  'Accept': 'text/event-stream, text/event-stream',
  'Accept-Language': 'en-US,en;q=0.5',
  'Referer': 'https://claude.ai/chats',
  'Content-Type': 'application/json',
  'Origin': 'https://claude.ai',
  'DNT': '1',
  'Connection': 'keep-alive',
  'Cookie': f'{self.cookie}',
  'Sec-Fetch-Dest': 'empty',
  'Sec-Fetch-Mode': 'cors',
  'Sec-Fetch-Site': 'same-origin',
  'TE': 'trailers'
}

response = requests.post(url, headers=headers, data=payload, stream=True)
decoded_data = response.content.decode("utf-8")
data_strings = decoded_data.strip().split('\n')
data_strings = [item for item in data_strings if item != '']
completions = []
for data_string in data_strings:
    json_str = data_string[6:].strip()
    data = json.loads(json_str)
    if 'completion' in data:
        completions.append(data['completion'])

answer = ''.join(completions)

# Returns answer
return answer
```

**Comment by KoushikNavuluri** [comment]
It's fixed now.Please update the package!
