### ISSUE TITLE
can not upload attachment

### ISSUE THREAD

**Issue by asyu17** [KoushikNavuluri/Claude-API#35]
can not upload attachment. The response code is 500.

The infomation of the file:
fe3b5879-3729-11ee-9e8a-165afc6b6ecb.txt
text/plain
{'file': ('fe3b5879-3729-11ee-9e8a-165afc6b6ecb.txt', <_io.BufferedReader name='./tmp_files/fe3b5879-3729-11ee-9e8a-165afc6b6ecb.txt'>, 'text/plain'), 'orgUuid': (None, '176ff333-3f38-4a03-a289-626369842e3b')}

**Comment by BlessingCR** [comment]
same problem

**Comment by KoushikNavuluri** [comment]
Hey, It's working fine at my end ! Please retry once and also try to update package to latest version.
