### ISSUE TITLE
Append Msg Err

### ISSUE THREAD

**Issue by BlessingCR** [KoushikNavuluri/Claude-API#37]
ClaudeAi add a header 'Baggage'  that looks like a kind of  security auth. 
Currently  version 1.0.14 unable to append msg.  I wonder when it will be updated, or how I can fix it quickly. 
I tested that getting this value from the browser and adding it to the header can make a successful request, but I can't get the return msg from Claude.

**Comment by kikmouu** [comment]
Hey, Even without that It's working fine at my end!

**Comment by KoushikNavuluri** [comment]
Hey, @BlessingCR  It's working fine even without that header.

**Comment by BlessingCR** [comment]
My Bad. 
It work  when i change another network env.
