### ISSUE TITLE
API Stopped Working

### ISSUE THREAD

**Issue by sumunna** [KoushikNavuluri/Claude-API#38]
The API stopped working 2 days ago. Getting the error below:

  self.organization_id = self.get_organization_id()
  File "/home/onezeusadmin/miniconda3/lib/python3.8/site-packages/claude_api.py", line 31, in get_organization_id
    uuid = res[0]['uuid']

Any Ideas?

**Comment by kikmouu** [comment]
Hey, @sumunna  It's working fine at my end!

**Comment by abulimen** [comment]
Make sure you are using the latest version. All I had to do to fix mine was to upgrade it.

**Comment by sumunna** [comment]
Thanks. I will upgrade.
