### ISSUE TITLE
Error: "We are unable to serve your request"

### ISSUE THREAD

**Issue by Lorg0n** [KoushikNavuluri/Claude-API#4]
At first I thought I had a problem with how I was saving the cookie to a variable. I was getting an error:
```Traceback (most recent call last):
  File "main.py", line 5, in <module>
    app = Client(cookie)
  File "\venv\lib\site-packages\claude_api.py", line 11, in __init__
    self.organization_id = self.get_organization_id()
  File "\venv\lib\site-packages\claude_api.py", line 32, in get_organization_id
    uuid = res[0]['uuid']
KeyError: 0
```

But after modifying your library a bit, I found the problem. The server just doesn't want to respond to my request:
`{'error': {'type': 'permission_error', 'message': 'We are unable to serve your request'}}`

My code looks like this:
```python
cookie = "sessionKey=****"

app = Client(cookie)
```
_* Instead of stars, my cookies_

**From the computer, Claude.ai is fully functional, no problems at all.**

**Comment by KoushikNavuluri** [comment]
Hey @Lorg0n Try this:

pip uninstall claude-api

pip install claude-api==1.0.8

and let me know if it works??

**Comment by Vallent16** [comment]
Hey, I still got the same error with similar code after installing the new version.

**Comment by KoushikNavuluri** [comment]
Hey , Did you place the whole cookie?? @Vallent16 
check the image below
![Screenshot (8)](https://github.com/KoushikNavuluri/Claude-API/assets/103725723/ea35b977-59e1-4a25-938c-08b592782cf8)

**Comment by Lorg0n** [comment]
The problem turned out to be on my side, not the library's. Because of my IP, the site wouldn't let me through, but when I ran the code from a virtual machine, everything worked.

**The strange thing is that everything works the same in the browser without VPN.**
