### ISSUE TITLE
I got the error

### ISSUE THREAD

**Issue by qiansheng2** [KoushikNavuluri/Claude-API#41]
Hi, thanks for your project.
But I found a error when I run the project,can you tell me the reason?

I got the session key from claude's website. and I write a test program:
------------------
from claude_api import Client

cookie = "sk-ant-sid01-W6my*********2cec14d2"
print(cookie)
claude_api = Client(cookie)

conversations = claude_api.list_all_conversations()
for conversation in conversations:
    conversation_id = conversation['uuid']
    print(conversation_id)
------------------    

When I run it, I got the error :

Traceback (most recent call last):
  File "/Users/nick/Claude-API/./test.py", line 8, in <module>
    claude_api = Client(cookie)
  File "/Users/nick/anaconda3/envs/llama2/lib/python3.10/site-packages/claude_api.py", line 12, in __init__
    self.organization_id = self.get_organization_id()
  File "/Users/nick/anaconda3/envs/llama2/lib/python3.10/site-packages/claude_api.py", line 32, in get_organization_id
    uuid = res[0]['uuid']
KeyError: 0

**Comment by qiansheng2** [comment]
I lost the “sessionKey” in the cookie。
The right thing is : cookie =  ”sessionKey=sk-ant******"

**Comment by ProgrammerFS** [comment]
I get the same error I tried all the api keys I could get but it still doesnt work i tried : 
sessionKey=sk-ant....;
intercom-device-id-...;
intercom-session-...;
__cf_bm=...;

I tried a combination of all of the above but nothing works pls help

**Comment by qiansheng2** [comment]
close

**Comment by ProgrammerFS** [comment]
> I missed the “sessionKey” in the cookie。 The right thing is : cookie = ”sessionKey=sk-ant******"

is it just the session key or is it a combination of both?

**Comment by sanjayshreeyans** [comment]
My code was working early morning, but it stopped working now. I am getting this error: {"type": "permission_error", "message": "We are unable to serve your request"}}. I haven't made any changes to the cookie, it randomly stopped working. I noticed that the code can still create a chat, but can't send a message and get a response back. Is there a fix to this problem? Do I have to use a VPN?

**Comment by theurs** [comment]
Yes, it stopped working again

**Comment by dinobby** [comment]
Same thing here, the exact same code worked in the morning and it stopped working now. I got `JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by RockChinQ** [comment]
> Same thing here, the exact same code worked in the morning and it stopped working now. I got `JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

me too.

```
[2023-08-16 10:17:42.035] main.py (168) - [ERROR] : [rev] Traceback (most recent call last):
  File "/root/QChatGPT/plugins/revLibs/main.py", line 136, in normal_message_received
    reply_message = procmsg.process_message(session_name=kwargs['launcher_type']+"_"+str(kwargs['launcher_id']),
  File "/root/QChatGPT/plugins/revLibs/pkg/process/procmsg.py", line 68, in process_message
    raise e
  File "/root/QChatGPT/plugins/revLibs/pkg/process/procmsg.py", line 39, in process_message
    for section in session.get_reply(prompt):
  File "/root/QChatGPT/plugins/revLibs/pkg/process/revss.py", line 113, in get_reply
    for reply_period_msg, reply_period_dict in self.__rev_interface_impl__.get_reply(prompt, **kwargs):
  File "/root/QChatGPT/plugins/revLibs/pkg/process/impls/claude.py", line 50, in get_reply
    resp = self.chatbot.send_message(prompt, self.conversation_id)
  File "/usr/local/lib/python3.9/site-packages/claude_api.py", line 128, in send_message
    data = json.loads(json_str)
  File "/usr/lib64/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
I've confirmd that the cookies is valid

**Comment by sanjayshreeyans** [comment]
Hi all, 

I think I may have found a workaround to fix the problem we're seeing with the Claude 2.0 module. After spending some time digging into the module code, I reverse engineered the network requests that the website frontend sends when chatting with Claude. 

By inspecting the Developer Tools Network tab, I was able to capture all the request headers being sent when appending a message, from `Accept` through `User-Agent`. I converted these headers into a JSON dictionary format. Note: I searched for the term `append_message` when filtering down the results.

Then, in the `claude_api.py` file, I replaced the `headers` dict in the `send_message` function with this JSON-formatted headers dictionary. 

This seems to have resolved the issues for now - the module is working again. It's likely not a complete fix, but a good temporary workaround. Let me know if you have any other ideas on how to properly address the root cause!

Thanks,
Sanjay Shreeyans Javangula

**Comment by dinobby** [comment]
> Hi all,
> 
> I think I may have found a workaround to fix the problem we're seeing with the Claude 2.0 module. After spending some time digging into the module code, I reverse engineered the network requests that the website frontend sends when chatting with Claude.
> 
> By inspecting the Developer Tools Network tab, I was able to capture all the request headers being sent when appending a message, from `Accept` through `User-Agent`. I converted these headers into a JSON dictionary format. Note: I searched for the term `append_message` when filtering down the results.
> 
> Then, in the `claude_api.py` file, I replaced the `headers` dict in the `send_message` function with this JSON-formatted headers dictionary.
> 
> This seems to have resolved the issues for now - the module is working again. It's likely not a complete fix, but a good temporary workaround. Let me know if you have any other ideas on how to properly address the root cause!
> 
> Thanks, Sanjay Shreeyans Javangula

Thanks for the update! Unfortunately this does not work for me :(
I found another way to bypass this temporarily using Selenium, although it can be much less efficient.
https://github.com/dinobby/claude-bot/blob/main/clauder.py

**Comment by wwwwar3com** [comment]
I used claude to do the conversion, it works for me:

        headers = {
            "authority": "claude.ai",
            "method": "POST",
            "path": "/sentry?o=1158394&p=4504646202490880",
            "scheme": "https",
            "Accept": "*/*",
            "Accept-Encoding": "gzip, deflate, br",
            "Accept-Language": "en-US,en;q=0.9",
            "Content-Length": "573",
            "Content-Type": "text/plain;charset=UTF-8",
            'Cookie': f'{self.cookie}',
            "Origin": "https://claude.ai",
            "Referer": "https://claude.ai/",
            "Sec-Ch-Ua": "\"Not/A)Brand\";v=\"99\", \"Google Chrome\";v=\"115\", \"Chromium\";v=\"115\"",
            "Sec-Ch-Ua-Mobile": "?0",
            "Sec-Ch-Ua-Platform": "\"Linux\"",
            "Sec-Fetch-Dest": "empty",
            "Sec-Fetch-Mode": "cors",
            "Sec-Fetch-Site": "same-origin",
            "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
        }

**Comment by winie-hy** [comment]
Have you found a new solution, my friends

**Comment by merlinarer** [comment]
> I used claude to do the conversion, it works for me:
> 
> ```
>     headers = {
>         "authority": "claude.ai",
>         "method": "POST",
>         "path": "/sentry?o=1158394&p=4504646202490880",
>         "scheme": "https",
>         "Accept": "*/*",
>         "Accept-Encoding": "gzip, deflate, br",
>         "Accept-Language": "en-US,en;q=0.9",
>         "Content-Length": "573",
>         "Content-Type": "text/plain;charset=UTF-8",
>         'Cookie': f'{self.cookie}',
>         "Origin": "https://claude.ai",
>         "Referer": "https://claude.ai/",
>         "Sec-Ch-Ua": "\"Not/A)Brand\";v=\"99\", \"Google Chrome\";v=\"115\", \"Chromium\";v=\"115\"",
>         "Sec-Ch-Ua-Mobile": "?0",
>         "Sec-Ch-Ua-Platform": "\"Linux\"",
>         "Sec-Fetch-Dest": "empty",
>         "Sec-Fetch-Mode": "cors",
>         "Sec-Fetch-Site": "same-origin",
>         "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
>     }
> ```

do not work for me :)

**Comment by wwwwar3com** [comment]
headers = {
  "authority": "claude.ai",
  "method": "GET",
  "path": f"/chat/{conversation_id}",
  "scheme": "https",
  "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
  "Accept-Encoding": "gzip, deflate, br",
  "Accept-Language": "en-US,en;q=0.9",
  "Cache-Control": "max-age=0",
  "Cookie": f'{self.cookie}',
      "Referer": "https://claude.ai/login",
  "Sec-Ch-Ua": "\"Not/A)Brand\";v=\"99\", \"Google Chrome\";v=\"115\", \"Chromium\";v=\"115\"",
  "Sec-Ch-Ua-Mobile": "?0",
  "Sec-Ch-Ua-Platform": "\"Linux\"",
  "Sec-Fetch-Dest": "empty",
  "Sec-Fetch-Mode": "navigate",
  "Sec-Fetch-Site": "same-origin",
  "Upgrade-Insecure-Requests": "1",
  "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
}

**Comment by wwwwar3com** [comment]
headers = {
  "authority": "claude.ai",
  "method": "GET",
  "path": f"/chat/{conversation_id}",
  "scheme": "https",
  "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
  "Accept-Encoding": "gzip, deflate, br",
  "Accept-Language": "en-US,en;q=0.9",
  "Cache-Control": "max-age=0",
  "Cookie": f'{self.cookie}',
      "Referer": "https://claude.ai/login",
  "Sec-Ch-Ua": "\"Not/A)Brand\";v=\"99\", \"Google Chrome\";v=\"115\", \"Chromium\";v=\"115\"",
  "Sec-Ch-Ua-Mobile": "?0",
  "Sec-Ch-Ua-Platform": "\"Linux\"",
  "Sec-Fetch-Dest": "empty",
  "Sec-Fetch-Mode": "navigate",
  "Sec-Fetch-Site": "same-origin",
  "Upgrade-Insecure-Requests": "1",
  "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
}
