### ISSUE TITLE
permission_error

### ISSUE THREAD

**Issue by merlinarer** [KoushikNavuluri/Claude-API#42]
I met the following error:
```
Traceback (most recent call last):
  File "xx.py", line 156, in <module>
    response = claude_api.send_message(prompt, conversation_id)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\app\miniconda3\Lib\site-packages\claude_api.py", line 130, in send_message
    data = json.loads(json_str)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\app\miniconda3\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\app\miniconda3\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\app\miniconda3\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
I found that the decoded data_strings is `['{"error": {"type": "permission_error", "message": "We are unable to serve your request"}}']`, while i can use the website as usual.

**Comment by sanjayshreeyans** [comment]
Hey, I found a temporary fix on here, #41

**Comment by merlinarer** [comment]
> Hey, I found a temporary fix on here, #41

thx, I will have a try.

**Comment by dinobby** [comment]
I've also written a simple script to address this using Selenium. Feel free to check [this script](https://github.com/dinobby/claude-bot/blob/main/clauder.py) and see if that works!

**Comment by wwwwar3com** [comment]
Nice I did sth similar but use Selenium to obstain the sessionkey , I found the key getting expired after while

**Comment by wwwwar3com** [comment]
@dinobby  does ffOptions.profile = FirefoxProfile('/Users/xxxxxx/Library/Application Support/Firefox/Profiles/xxxxxx.default-release')
enables the stored credential to auto login to claude? that's neat,

**Comment by dinobby** [comment]
> @dinobby does ffOptions.profile = FirefoxProfile('/Users/xxxxxx/Library/Application Support/Firefox/Profiles/xxxxxx.default-release') enables the stored credential to auto login to claude? that's neat,

Yes, so you don't have to handle those login processes with code, it's quite annoying to debug 😌

**Comment by merlinarer** [comment]
> > @dinobby does ffOptions.profile = FirefoxProfile('/Users/xxxxxx/Library/Application Support/Firefox/Profiles/xxxxxx.default-release') enables the stored credential to auto login to claude? that's neat,
> 
> Yes, so you don't have to handle those login processes with code, it's quite annoying to debug 😌

Does this support none-local profile? such as profile in sever A to use in sever B?

**Comment by elcarim** [comment]
Traceback (most recent call last):
  File "w:\py\claude\claude.py", line 6, in <module>
    claude_api = Client(cookie)
                 ^^^^^^^^^^^^^^
  File "W:\py\claude\_venv\Lib\site-packages\claude_api.py", line 12, in __init__
    self.organization_id = self.get_organization_id()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "W:\py\claude\_venv\Lib\site-packages\claude_api.py", line 32, in get_organization_id
    uuid = res[0]['uuid']
           ~~~^^^
KeyError: 0

**Comment by Scarecrow1024** [comment]
> Hey, I found a temporary fix on here, #41

dont work

**Comment by winie-hy** [comment]
No effect by modifying the header

**Comment by wwwwar3com** [comment]
headers = {
      "authority": "claude.ai",
      "method": "GET",
      "path": f"/chat/{conversation_id}",
      "scheme": "https",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.9",
      "Cache-Control": "max-age=0",
      "Cookie": f'{self.cookie}',
          "Referer": "https://claude.ai/login",
      "Sec-Ch-Ua": "\"Not/A)Brand\";v=\"99\", \"Google Chrome\";v=\"115\", \"Chromium\";v=\"115\"",
      "Sec-Ch-Ua-Mobile": "?0",
      "Sec-Ch-Ua-Platform": "\"Linux\"",
      "Sec-Fetch-Dest": "empty",
      "Sec-Fetch-Mode": "navigate",
      "Sec-Fetch-Site": "same-origin",
      "Upgrade-Insecure-Requests": "1",
      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
    }

**Comment by RyanCRF** [comment]
I have met the same problem. Waiting for solutions. 
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by ProgrammerFS** [comment]
I have the following error : {'error': {'type': 'permission_error', 'message': 'We are unable to serve your request'}}

I have given the correct cookie

**Comment by winie-hy** [comment]
还有解救的思路或者方法吗，

**Comment by KoushikNavuluri** [comment]
Getting it fixed! Working on it right now, Mostly will be fixed by tomorrow.

**Comment by elcarim** [comment]
how to automate the process, so as not to constantly copy cookies and session key?

**Comment by merlinarer** [comment]
> Getting it fixed! Working on it right now, Mostly will be fixed by tomorrow.

cannot wait !

**Comment by techmedok** [comment]
Do something with cookies. taking cookies is a tedious task. just make it like passing just the cookie instead of entire header value.

**Comment by flyinsea** [comment]
同样暂时不可用，所有其他用web方式调用API的都处于不可用状态

**Comment by zczhuohuo** [comment]
may be you should try https://github.com/yifeikong/curl_cffi to request claude.ai

**Comment by KoushikNavuluri** [comment]
Hey guys, The issue has been fixed . Please upgrade the package to latest version (1.0.15) to get rid of error.
Please give a star if you like and also please do follow and support. 😄 !!
