### ISSUE TITLE
Timeout on big requests

### ISSUE THREAD

**Issue by theurs** [KoushikNavuluri/Claude-API#45]
Thanks for fix, it works again.

I got this error now when I ask to summarize large text (99k letters)

It was fine in previous versions

my_claude:chat_request: Failed to perform, ErrCode: 28, Reason: 'Operation timed out after 30001 milliseconds with 0 bytes received'                                          
my_claude:chat_request:error2: Failed to perform, ErrCode: 28, Reason: 'Operation timed out after 30000 milliseconds with 28196 bytes received'

**Comment by zaojingyoutu** [comment]
> 

添加超时时间

**Comment by zaojingyoutu** [comment]
> Hey, @theurs Its was good at my end, but okay considered this and will look into it and fix it soon.

使用的curl_cffi 库支持stream吗？现在需要等全部数据返回以后才响应，有些慢了。

**Comment by elcarim** [comment]
Ошибка при выполнении запроса: Failed to perform, ErrCode: 28, Reason: 'Operation timed out after 30000 milliseconds with 76825 bytes received'

**Comment by KoushikNavuluri** [comment]
> added timeout=90 to every request and its fixed default was None (=30)

Cool! Will Try to add in code too! 🤗

**Comment by KoushikNavuluri** [comment]
> > Hey,@theursIts was good at my end, but okay considered this and will look into it and fix it soon.
> 
> Does the curl_cffi library used support stream? Now it needs to wait for all the data to be returned before responding, which is a bit slow.

Yeah , I am currently experimenting out file handling and streaming messages, will soon update it next version !!!

**Comment by zaojingyoutu** [comment]
> > > Hey,@theursIts was good at my end, but okay considered this and will look into it and fix it soon.
> > 
> > 
> > Does the curl_cffi library used support stream? Now it needs to wait for all the data to be returned before responding, which is a bit slow.
> 
> Yeah , I am currently experimenting out file handling and streaming messages, will soon update it next version !!!

def stream_content(resp):
            print(resp)
            yield resp.decode('utf-8')
        response = requests.request("POST", url, json=payload, headers=self.headers,impersonate="chrome110",timeout=600,content_callback=stream_content)  这种可以实现，但是我用的是fastapi 还有些问题没有解决

**Comment by KoushikNavuluri** [comment]
> > > > Hey,@theursIts was good at my end, but okay considered this and will look into it and fix it soon.
> > > 
> > > 
> > > Does the curl_cffi library used support stream? Now it needs to wait for all the data to be returned before responding, which is a bit slow.
> > 
> > 
> > Yeah , I am currently experimenting out file handling and streaming messages, will soon update it next version !!!
> 
> def stream_content(resp): print(resp) yield resp.decode('utf-8') response = requests.request("POST", url, json=payload, headers=self.headers, impersonate="chrome110", timeout =600,content_callback=stream_content) This can be achieved, but I use fastapi and there are still some problems that have not been resolved

Will check and try this out!!! :)

**Comment by KoushikNavuluri** [comment]
Hey Guys, File handling and other issues has been fixed ,Please Update to Package == 1.0.16.

:)

**Comment by elcarim** [comment]
Requirement already satisfied: claude_api in w:\py\claude\_venv\lib\site-packages (1.0.16)
Requirement already satisfied: requests in w:\py\claude\_venv\lib\site-packages (from claude_api) (2.31.0)
Requirement already satisfied: curl-cffi in w:\py\claude\_venv\lib\site-packages (from claude_api) (0.5.7)
Requirement already satisfied: cffi>=1.12.0 in w:\py\claude\_venv\lib\site-packages (from curl-cffi->claude_api) (1.15.1)
Requirement already satisfied: charset-normalizer<4,>=2 in w:\py\claude\_venv\lib\site-packages (from requests->claude_api) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in w:\py\claude\_venv\lib\site-packages (from requests->claude_api) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in w:\py\claude\_venv\lib\site-packages (from requests->claude_api) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in w:\py\claude\_venv\lib\site-packages (from requests->claude_api) (2023.7.22)
Requirement already satisfied: pycparser in w:\py\claude\_venv\lib\site-packages (from cffi>=1.12.0->curl-cffi->claude_api) (2.21)

 Failed to perform, ErrCode: 28, Reason: 'Operation timed out after 30000 milliseconds with 68619 bytes received'
limit start

**Comment by emsi** [comment]
> Hey Guys, File handling and other issues has been fixed ,Please Update to Package == 1.0.16.
> 
> :)

It doesn't seem like the timeout was addressed in this release

**Comment by theurs** [comment]
> Requirement already satisfied: claude_api in w:\py\claude_venv\lib\site-packages (1.0.16) Requirement already satisfied: requests in w:\py\claude_venv\lib\site-packages (from claude_api) (2.31.0) Requirement already satisfied: curl-cffi in w:\py\claude_venv\lib\site-packages (from claude_api) (0.5.7) Requirement already satisfied: cffi>=1.12.0 in w:\py\claude_venv\lib\site-packages (from curl-cffi->claude_api) (1.15.1) Requirement already satisfied: charset-normalizer<4,>=2 in w:\py\claude_venv\lib\site-packages (from requests->claude_api) (3.2.0) Requirement already satisfied: idna<4,>=2.5 in w:\py\claude_venv\lib\site-packages (from requests->claude_api) (3.4) Requirement already satisfied: urllib3<3,>=1.21.1 in w:\py\claude_venv\lib\site-packages (from requests->claude_api) (2.0.4) Requirement already satisfied: certifi>=2017.4.17 in w:\py\claude_venv\lib\site-packages (from requests->claude_api) (2023.7.22) Requirement already satisfied: pycparser in w:\py\claude_venv\lib\site-packages (from cffi>=1.12.0->curl-cffi->claude_api) (2.21)
> 
> Failed to perform, ErrCode: 28, Reason: 'Operation timed out after 30000 milliseconds with 68619 bytes received' limit start

тебе надо вручную пропатчить. скачать и сохранить в папку проекта и там найти все requests. и добавить timeout=90

**Comment by theurs** [comment]
> > в исходниках curl_cffi ничего такого нет
> 
> можете уточнить где менять нужно? а то я не пойму. менял в claude_api.py

Да там. А где там переменные окружения?

**Comment by KoushikNavuluri** [comment]
Hello All, Fixed the Timeout Errors ,Added Timeout Parameter to send_message ,you can set custom timeouts and also default timeout has been increased.

Thank you! :)

**Comment by elcarim** [comment]
> > > в исходниках curl_cffi ничего такого нет
> > 
> > 
> > можете уточнить где менять нужно? а то я не пойму. менял в claude_api.py
> 
> Да там. А где там переменные окружения?

у  вас работает? у меня даже 17 версия все равно не работает!

**Comment by theurs** [comment]
> > > > в исходниках curl_cffi ничего такого нет
> > > 
> > > 
> > > можете уточнить где менять нужно? а то я не пойму. менял в claude_api.py
> > 
> > 
> > Да там. А где там переменные окружения?
> 
> у вас работает? у меня даже 17 версия все равно не работает!

работает. версия в которой еще не пофиксили загрузку файлов и что там еще было. я просто добавил таймаутов и всё https://github.com/theurs/tb1/blob/master/claude_api.py

**Comment by theurs** [comment]
> > > > в исходниках curl_cffi ничего такого нет
> > > 
> > > 
> > > можете уточнить где менять нужно? а то я не пойму. менял в claude_api.py
> > 
> > 
> > Да там. А где там переменные окружения?
> 
> у вас работает? у меня даже 17 версия все равно не работает!

работает. версия в которой еще не пофиксили загрузку файлов и что там еще было. я просто добавил таймаутов и всё (ну и еще в конструктор добавил прокси, просто для совместимости, оно не используется)
https://github.com/theurs/tb1/blob/master/claude_api.py

у меня оно в основном для пересказа длинных текстов используется. но и для чата тоже можно. оба варианта работают


https://www.youtube.com/watch?v=YWS123UnFvI

Основные моменты лекции:

- Иммунитет делится на врожденный и приобретенный. 

- Врожденный иммунитет работает сразу после рождения, а приобретенный формируется в течение жизни.

- Ключевые клетки иммунитета - лимфоциты, которые вырабатывают антитела. Антитела распознают чужеродные молекулы - антигены. 

- Фагоциты поглощают бактерии и вирусы, а натуральные киллеры убивают зараженные клетки.

- Вакцины вводят антигены, чтобы сформировать иммунитет, не переболевая болезнью. 

- При аллергии иммунная система реагирует на безобидные вещества.

- Аутоиммунные заболевания возникают из-за реакции иммунитета на собственные клетки и белки.

- Рак часто развивается из-за ошибок иммунитета, но иногда иммунная система может сама уничтожать опухоли.

--
Claude - Anthropic [89068 символов]

**Comment by elcarim** [comment]
https://github.com/theurs/tb1/blob/master/claude_api.py

ну так я выше про автозамену писал, как раз здесь и правил., но у меня всеравно не работает. 
для того что вы делали можно ХАРПУ использовать.
