### ISSUE TITLE
403Forbidden

### ISSUE THREAD

**Issue by qiansheng2** [KoushikNavuluri/Claude-API#46]
Hi, thanks for KoushikNavuluri‘s api.
I tested this api, but I met the forbidden error by this:
![image](https://github.com/KoushikNavuluri/Claude-API/assets/5198358/6c0acdf0-826f-4314-bb4c-cb8cb93f064a)

Test env:
1. My computer(Macbook M1pro) in china , access the claude by America's proxy server.
2. The server in America(azure cloud ,ubuntu 20.04).
I got the same error in 2 envs.

Have you any advice?

Best regards.

**Comment by qiansheng2** [comment]
I can use this sessionkey by my chrom web browser. It's ok in the browser.

**Comment by RyanCRF** [comment]
It works for me. The author has updated the claude_api version a few minutes ago, which solved the "permission error" in #42 . Maybe you can update it to version 1.0.15 and have a try.  Good luck!

**Comment by KoushikNavuluri** [comment]
### Please Update the Package to version 1.0.15!! 

> Hi, thanks for KoushikNavuluri‘s api. I tested this api, but I met the forbidden error by this: ![image](https://user-images.githubusercontent.com/5198358/261256448-6c0acdf0-826f-4314-bb4c-cb8cb93f064a.png)
> 
> Test env:
> 
> 1. My computer(Macbook M1pro) in china , access the claude by America's proxy server.
> 2. The server in America(azure cloud ,ubuntu 20.04).
>    I got the same error in 2 envs.
> 
> Have you any advice?
> 
> Best regards.

**Comment by KoushikNavuluri** [comment]
Hey Guys, File handling and other issues has been fixed ,Please Update to Package == 1.0.16.

:)
