### ISSUE TITLE
cannot even create a new chat with the newest version

### ISSUE THREAD

**Issue by HQ-Zhang-233** [KoushikNavuluri/Claude-API#48]
Traceback (most recent call last):
  File "D:\test pj\claude\cltest.py", line 6, in <module>
    claude_api = Client(cookie)
  File "D:\test pj\LCplayGround\lib\site-packages\claude_api.py", line 12, in __init__
    self.organization_id = self.get_organization_id()
  File "D:\test pj\LCplayGround\lib\site-packages\claude_api.py", line 31, in get_organization_id
    res = json.loads(response.text)
  File "C:\Users\zhq\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\zhq\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\zhq\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 9 (char 9)

the version of this package is 1.0.15

**Comment by KoushikNavuluri** [comment]
It's working fine at my end, Can you please check package version and cookie placement too!!

**Comment by HQ-Zhang-233** [comment]
![image](https://github.com/KoushikNavuluri/Claude-API/assets/48396988/01aa1f29-397e-44db-a121-ad114a1eb8d0)
sorry but i really cannot run this in my end~

**Comment by KoushikNavuluri** [comment]
Did you place the whole cookie like here:
 (Checkout below image for the format of cookie )

   ![Screenshot (8)](https://github.com/KoushikNavuluri/Claude-API/assets/103725723/355971e3-f46c-47fc-a3cf-008bb55bb4c6)

**Comment by HQ-Zhang-233** [comment]
sorry, my fault , it seems i add a wrong code 
 cookie = os.environ.get('cookie')
 
 after delete this code
 i got this error
 
 raise error
curl_cffi.curl.CurlError: Failed to perform, ErrCode: 35, Reason: 'BoringSSL SSL_connect: SSL_ERROR_SYSCALL in connection to anthropic.com:443 '

**Comment by KoushikNavuluri** [comment]
Are you using any VPN??

**Comment by HQ-Zhang-233** [comment]
yes, i am in China and have to use VPNs to get connect with Claude

**Comment by KoushikNavuluri** [comment]
Try executing once without VPN! I am from India, I made whole API Without VPN :) (Except while account creation)
