### ISSUE TITLE
How to upload files?

### ISSUE THREAD

**Issue by Hongbin98** [KoushikNavuluri/Claude-API#5]
First of all, thanks for your work! It did help me a lot :)

I wonder if it is able to upload files and chat with Claude?

Looking for your reply.

**Comment by KoushikNavuluri** [comment]
Hello  @Hongbin98 , Have been updated code with other cool features . 
You can check how to upload files here in the documentation of my code:
https://github.com/KoushikNavuluri/Claude-API/#send-message-with-attachment
Please update the package ,before you try this :
` pip install --upgrade claude-api `
