### ISSUE TITLE
Organization ID issue

### ISSUE THREAD

**Issue by matteo-chevalier** [KoushikNavuluri/Claude-API#52]
Hi I tried all cookies I found, tried to merged all together and I nothing happened. 

Cannot find the issue :/

<img width="732" alt="Capture d’écran 2023-08-17 à 13 55 44" src="https://github.com/KoushikNavuluri/Claude-API/assets/84286598/ed597e5d-997e-45a7-a276-86eefaadf79b">

<img width="1090" alt="Capture d’écran 2023-08-17 à 13 35 26" src="https://github.com/KoushikNavuluri/Claude-API/assets/84286598/07dbd8ce-d339-497f-95d0-b45a124de724">

**Comment by Haris-Dilawar** [comment]
try 
calude_api = Client('your cookie')

**Comment by KoushikNavuluri** [comment]
Check whether you have placed the whole cookie as shown in image at readme file or docs.
