### ISSUE TITLE
Timeout error （1.0.16）

### ISSUE THREAD

**Issue by qiansheng2** [KoushikNavuluri/Claude-API#53]
Thanks for rapid versionup!
After I updated to the version of 1.0.16，I still got this error:
<img width="1002" alt="image" src="https://github.com/KoushikNavuluri/Claude-API/assets/5198358/0a74ac2c-2287-4fb1-84cd-b00e4339dfe4">

How to set up the timeout ?

**Comment by RyanCRF** [comment]
I met the same problem. 

RequestsError: Failed to perform, ErrCode: 28, Reason: 'Operation timed out after 30002 milliseconds with 22179 bytes received'

**Comment by HQ-Zhang-233** [comment]
same error +1

**Comment by Lxb921006** [comment]
There seems to be no solution to this

**Comment by KoushikNavuluri** [comment]
Hey guys , It seems many has requested timeout param , will be fixed to next version very soon. Also Implementing some exceptions in next update too!

**Comment by KoushikNavuluri** [comment]
Hello All, Fixed the Timeout Errors ,Added Timeout Parameter to send_message ,you can set custom timeouts and also default timeout has been increased.

Thank you! :)
