### ISSUE TITLE
claude_api = Client(cookie)->Traceback (most recent call last):   File "/root/chat-claude-2.py", line 4, in <module>     claude_api = Client(cookie)   File "/data/env/chat/lib/python3.9/site-packages/claude_api.py", line 13, in __init__     self.organization_id = self.get_organization_id()   File "/data/env/chat/lib/python3.9/site-packages/claude_api.py", line 33, in get_organization_id     uuid = res[0]['uuid'] KeyError: 0

### ISSUE THREAD

**Issue by Lxb921006** [KoushikNavuluri/Claude-API#56]
There's still a problem

**Comment by KoushikNavuluri** [comment]
Check Your Cookie Placement, Whether have you placed whole cookie?

**Comment by NonaryR** [comment]
I confirm this issue, why you are closing it without resolving?

**Comment by NonaryR** [comment]
NOBODY puts `sessionKey=sk-ant-si...` sessionKey in cookie, this is why you have so many issues about that
take a look here, for example https://github.com/Explosion-Scratch/claude-unofficial-api

**Comment by KoushikNavuluri** [comment]
Hello , @NonaryR As it seems many have encountered such error, And I responded them with the solution of whole cookie placement , Then it worked fine for all . Second thing is you have mentioned the other packages , recently after Claude made many changes in its API, Only mine(this package) is only currently active and working perfectly!

Thanks and Please let me know if you have any issue , will try to resolve it . 😄 !
