### ISSUE TITLE
Streaming?

### ISSUE THREAD

**Issue by a2ronprice** [KoushikNavuluri/Claude-API#58]
Saw an old issue surrounding streaming support and the additional method stream_message(). But noticed it's no longer part of the library. Is this coming back soon?
<img width="539" alt="ClaudeStream" src="https://github.com/KoushikNavuluri/Claude-API/assets/107771768/16edfa76-6849-4555-9aa4-2437ca5469c0">
<img width="495" alt="ClaudeStream2" src="https://github.com/KoushikNavuluri/Claude-API/assets/107771768/48cf6dc3-153d-4b84-97aa-c5193c9c5c71">

**Comment by KoushikNavuluri** [comment]
Yet to implement streaming support again! will be updated soon in the next version of update!
