### ISSUE TITLE
key error

### ISSUE THREAD

**Issue by xRiddin** [KoushikNavuluri/Claude-API#59]
claude = Client(SESSION_KEY)
  File "/Users/apple/PycharmProjects/pythonProject/IKYET/ikyet_render/models/claude_api.py", line 13, in __init__
    self.organization_id = self.get_organization_id()
  File "/Users/apple/PycharmProjects/pythonProject/IKYET/ikyet_render/models/claude_api.py", line 33, in get_organization_id
    uuid = res[0]['uuid']
KeyError: 0

**Comment by xRiddin** [comment]
{'error': {'type': 'permission_error', 'message': 'Invalid authorization'}}

**Comment by yeti-yeti** [comment]
me too.

**Comment by t4stek1ng** [comment]
it means claude can't use in your region. please try to use a proxy to get connect. )

**Comment by KoushikNavuluri** [comment]
> claude = Client(SESSION_KEY) File "/Users/apple/PycharmProjects/pythonProject/IKYET/ikyet_render/models/claude_api.py", line 13, in **init** self.organization_id = self.get_organization_id() File "/Users/apple/PycharmProjects/pythonProject/IKYET/ikyet_render/models/claude_api.py", line 33, in get_organization_id uuid = res[0]['uuid'] KeyError: 0

Please place the "whole cookie" ,not just sessionkey. Check readme docs for cookie placement help. 
(Also dont use VPN, Most requests from VPN's are blocked by claude servers. "Even if you are from other countries this api works without VPN".)
