### ISSUE TITLE
can not upload pdf files as attachment

### ISSUE THREAD

**Issue by chemyibinjiang** [KoushikNavuluri/Claude-API#61]
I'm trying to use claude to summarize pdf files for me. When I put the path to the pdf file, it shows me the error:
`{'Error: Invalid file format. Please try again.'}`

The code I used it below:
```
conversation_id = claude_api.create_new_chat()['uuid']
response = claude_api.send_message("hello", 
                                   conversation_id,
                                   attachment = "./ja500330a.pdf")
print(response)
```

This pdf file can be read normally through the website of claude. Any clue what is going on?

**Comment by KoushikNavuluri** [comment]
Hey, It's working fine at my end.Try inserting whole path and check.

**Comment by chemyibinjiang** [comment]
No, it's not working by putting the full path. I look into the response and it says ERROR 404.

**Comment by Muhammad-Anas-Younus** [comment]
Hey @chemyibinjiang, I was facing a similar issue and this is what fixed it for me.
1. Make sure that your file name does not have any special characters like _, ! etc 
2. Add r prefix before your absolute path, like this : r"E:\folder\folder\folder\sample.pdf"
