### ISSUE TITLE
HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by y80x86ol** [KoushikNavuluri/Claude-API#66]
When I use the start_new_conversation function, it will prompt me "HTTP Error 403: Forbidden" error. 

I have upgraded to the latest version 1.0.16 and still have this problem. 

Please check it out, thank you very much.

**Comment by RyanCRF** [comment]
The latest version is 1.0.17. Please update to the current version and remember to use new cookies. Hopefully, it will solve your issue.

**Comment by KoushikNavuluri** [comment]
> 

Please update the latest version .
