### ISSUE TITLE
Cookie become invalid qiuckly

### ISSUE THREAD

**Issue by merlinarer** [KoushikNavuluri/Claude-API#69]
Hey, guys~ I found my cookie become invalid qiuckly, about in a day, even I verify my acount with my phone number. Have you met the issue?

**Comment by winie-hy** [comment]
I have encountered the same problem, and I want to know how to remove the rate limit and expiration problem. Can I remove the rate problem through multiple account switching? Can I generate cookies in the form of code

**Comment by zjttfs** [comment]
I have tried using multiple different account cookies in rotation, but they all become invalid very quickly.

**Comment by Luvata** [comment]
My cookie is still alive for more than a week. I guess don't sign out

**Comment by merlinarer** [comment]
> 

Acoording to my practice, 1 request every 10 mins for one acount could avoid rate limitation.

**Comment by merlinarer** [comment]
> My cookie is still alive for more than a week. I guess don't sign out

Yeah, my cookie has keeping alive for about a month, but suddenly became invalid yesterday. My new cookie also expirated just in one day. I guess the Claude has taken some new strategies.

**Comment by KoushikNavuluri** [comment]
Cookies are valid until you signout. so please make sure you don't signout or replace  new cookies.
And While using Vpn ,the observations seems cookies are being changed, please try to avoid using VPN's.
