### ISSUE TITLE
JSONDecodeError in list_all_conversations 

### ISSUE THREAD

**Issue by merlinarer** [KoushikNavuluri/Claude-API#71]
when I run the codes below:
```
conversations = claude_api.list_all_conversations()
for conversation in conversations:
     conversation_id = conversation['uuid']
```
I met the error `*** json.decoder.JSONDecodeError: Expecting value: line 2 column 9 (char 9)`. It is beacause returned `response = requests.get(url, headers=headers,impersonate="chrome110")`  is not a json but a html str. How to fix it ?

**Comment by Randomboiii03** [comment]
> when I run the codes below:
> 
> ```
> conversations = claude_api.list_all_conversations()
> for conversation in conversations:
>      conversation_id = conversation['uuid']
> ```
> 
> I met the error `*** json.decoder.JSONDecodeError: Expecting value: line 2 column 9 (char 9)`. It is beacause returned `response = requests.get(url, headers=headers,impersonate="chrome110")` is not a json but a html str. How to fix it ?

It works for me though, change your cookie if it fix the issue

**Comment by KoushikNavuluri** [comment]
Please check your cookie, whether you have placed right?!

**Comment by joostshao** [comment]
limited

**Comment by joostshao** [comment]
![image](https://github.com/KoushikNavuluri/Claude-API/assets/3615951/38b72f7f-fee5-4536-8c9f-6760959101b0)
