### ISSUE TITLE
I get an error when using claude_api.send_message()

### ISSUE THREAD

**Issue by xiewenqian** [KoushikNavuluri/Claude-API#75]
[/usr/lib/python3.10/json/decoder.py](https://localhost:8080/#) in raw_decode(self, s, idx)
    353             obj, end = self.scan_once(s, idx)
    354         except StopIteration as err:
--> 355             raise JSONDecodeError("Expecting value", s, err.value) from None
    356         return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**I can get the conversation_id normally**
![image](https://github.com/KoushikNavuluri/Claude-API/assets/6766800/5c46de20-fc61-4029-815b-beab5f0ae16a)

**Comment by winie-hy** [comment]
I got the same error at 10 o 'clock

**Comment by winie-hy** [comment]
@KoushikNavuluri Can I help fix it

**Comment by winie-hy** [comment]
After a while, it seemed to automatically recover?

**Comment by xiewenqian** [comment]
My test here was also successful.
