### ISSUE TITLE
my account has been blocked

### ISSUE THREAD

**Issue by xiewenqian** [KoushikNavuluri/Claude-API#80]
![image](https://github.com/KoushikNavuluri/Claude-API/assets/6766800/1b1780cf-3bc2-4d5d-9dbb-2e47db4153d7)

**Comment by joachimBrindeau** [comment]
Did you query a lot?
What did you do?

**Comment by xiewenqian** [comment]
Maybe it's because I used colab to run the code

**Comment by xiewenqian** [comment]
.
